CXX = cl.exe
CXXFLAGS = /EHsc /std:c++14 /utf-8 /c /wd4819 /wd4828 /Fo"obj\\" /Fd"obj\\" /nologo /Zi /Od /MDd /RTC1

CORE_OBJS = obj\analyzer.obj obj\SFI.obj obj\xyz.obj obj\parser.obj obj\sheet.obj obj\dictionary.obj obj\automata.obj obj\printer.obj obj\analyzerthread_win.obj obj\template.obj obj\SFI_v02_core.obj obj\SFI_v02_element_data.obj obj\SFI_v02_task.obj
OBJS = obj\main.obj obj\test.obj obj\test_sfi_v02.obj $(CORE_OBJS)

all: test\main.exe

test\main.exe: $(OBJS)
        link.exe /nologo /DEBUG /OUT:"test\main.exe" $(OBJS)

obj\main.obj: test\main.cpp
        if not exist obj mkdir obj
        $(CXX) $(CXXFLAGS) test\main.cpp

obj\test.obj: test\test.cpp
        if not exist obj mkdir obj
        $(CXX) $(CXXFLAGS) test\test.cpp

obj\test_sfi_v02.obj: test\test_sfi_v02.cpp code\SFI_v02\sfi_v02.h code\SFI_v02\element_data.h
        if not exist obj mkdir obj
        $(CXX) $(CXXFLAGS) /Fo"obj\test_sfi_v02.obj" test\test_sfi_v02.cpp

obj\analyzer.obj: code\analyzer.cpp code\analyzer.h
        if not exist obj mkdir obj
        $(CXX) $(CXXFLAGS) code\analyzer.cpp

obj\SFI.obj: code\SFI.cpp code\analyzer.h
        if not exist obj mkdir obj
        $(CXX) $(CXXFLAGS) code\SFI.cpp

obj\SFI_v02_core.obj: code\SFI_v02\sfi_v02.cpp code\SFI_v02\sfi_v02.h code\analyzer.h
        if not exist obj mkdir obj
        $(CXX) $(CXXFLAGS) /Fo"obj\SFI_v02_core.obj" code\SFI_v02\sfi_v02.cpp

obj\SFI_v02_element_data.obj: code\SFI_v02\element_data.cpp code\SFI_v02\element_data.h
        if not exist obj mkdir obj
        $(CXX) $(CXXFLAGS) /Fo"obj\SFI_v02_element_data.obj" code\SFI_v02\element_data.cpp

obj\SFI_v02_task.obj: code\SFI_v02\task.cpp code\SFI_v02\task.h code\SFI_v02\sfi_v02.h code\SFI_v02\element_data.h code\dictionary.h
        if not exist obj mkdir obj
        $(CXX) $(CXXFLAGS) /Fo"obj\SFI_v02_task.obj" code\SFI_v02\task.cpp

obj\xyz.obj: code\xyz.cpp code\analyzer.h
        if not exist obj mkdir obj
        $(CXX) $(CXXFLAGS) code\xyz.cpp

obj\parser.obj: code\parser.cpp code\analyzer.h
        if not exist obj mkdir obj
        $(CXX) $(CXXFLAGS) code\parser.cpp

obj\sheet.obj: code\sheet.cpp code\sheet.h
        if not exist obj mkdir obj
        $(CXX) $(CXXFLAGS) code\sheet.cpp

obj\dictionary.obj: code\dictionary.cpp code\dictionary.h
        if not exist obj mkdir obj
        $(CXX) $(CXXFLAGS) code\dictionary.cpp

obj\automata.obj: code\automata.cpp code\automata.h
        if not exist obj mkdir obj
        $(CXX) $(CXXFLAGS) code\automata.cpp

obj\printer.obj: code\printer.cpp code\analyzer.h
        if not exist obj mkdir obj
        $(CXX) $(CXXFLAGS) code\printer.cpp

obj\analyzerthread_win.obj: code\analyzerthread_win.cpp code\analyzer.h
        if not exist obj mkdir obj
        $(CXX) $(CXXFLAGS) code\analyzerthread_win.cpp

obj\template.obj: code\template.cpp code\template.h
        if not exist obj mkdir obj
        $(CXX) $(CXXFLAGS) code\template.cpp

benchmark-sfi-v02: test\benchmark-sfi-v02.exe

test\benchmark-sfi-v02.exe: $(CORE_OBJS) obj\benchmark_sfi_v02.obj
        link.exe /nologo /DEBUG /OUT:"test\benchmark-sfi-v02.exe" $(CORE_OBJS) obj\benchmark_sfi_v02.obj

obj\benchmark_sfi_v02.obj: test\benchmark_sfi_v02.cpp code\SFI_v02\sfi_v02.h code\analyzer.h
        if not exist obj mkdir obj
        $(CXX) $(CXXFLAGS) /Fo"obj\benchmark_sfi_v02.obj" test\benchmark_sfi_v02.cpp

clean:
        if exist obj\*.obj del /Q obj\*.obj
        if exist test\main.exe del /Q test\main.exe
